# Change these first
owner: denesg1
repo: upptime # The name of this repository

sites: # List of endpoints to track
  - name: Google
    url: https://www.google.com
assignees: # Users to assign downtime issues (optional)
  - AnandChowdhary
status-website: # Status website (optional)
  cname: upptime.js.org # Custom domain CNAME
  name: Upptime # Status website title

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
