owner: denesg1 # GitHub username
repo: upptime # GitHub repository name
sites: # List of endpoints to track
  - name: DA website
    url: https://digitalarcher.dev
status-website: # Status website (optional)
  name: DA statuses # Status website title
  theme: dark
  introTitle: "DA stasuses powered by Uptime.js.org tool"
  introMessage: "This is an intro message"
  
